import React from 'react';
export interface ScoreboardInterface {}

const Scoreboard : React.FC<ScoreboardInterface> = () => {
	return <div>
		Scoreboard
		<p>Lorem Ipsum
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard 
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard 
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard 
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard 
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard 
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard 
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		ScoreboardScoreboardScoreboardScoreboardScoreboardScoreboardScoreboard
		
		</p>
		</div>;
};

export default Scoreboard;
